# Generated by Django 6.0.4 on 2026-10-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_full_name_order_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('qr', 'Chuyển khoản bằng QR'), ('mock', 'Thanh toán online mô phỏng')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('awaiting_transfer', 'Chờ chuyển khoản'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
